services:
    boardtalk.fixedmenu.listener:
        class: boardtalk\fixedmenu\event\main_listener
        arguments:
            - @controller.helper
            - @template
            - @config
        tags:
            - { name: event.listener }
